### ISSUE TITLE
question about training on selected subset

### ISSUE THREAD

**Issue by zhangxin-xd** [ZhenyuTANG2023/data_selection#1]
Hi, thanks for sharing your excellent work. I noticed that you mention "For all the experiments, we initialize image classification models (pre-trained on ImageNet) using weights in Torchvision for faster and more stable convergence". Does that mean the training on the selected subset is not from scratch but based on pre-trained weights?

**Comment by ZhenyuTANG2023** [comment]
Yes, the results in the paper is based on pre-trained weights.

**Comment by ZhenyuTANG2023** [comment]
Yes, the results in the paper are based on pre-trained weights.

**Comment by zhangxin-xd** [comment]
Thank you for replying!
---- Replied Message ----
| From | ***@***.***> |
| Date | 07/28/2023 18:59 |
| To | ZhenyuTANG2023/data_selection ***@***.***> |
| Cc | zhangxin-xd ***@***.***>,
Author ***@***.***> |
| Subject | Re: [ZhenyuTANG2023/data_selection] question about training on selected subset (Issue #1) |

Yes, the results in the paper are based on pre-trained weights.
