### ISSUE TITLE
petrel_client is not installed, petrel oss cannot be used currently

### ISSUE THREAD

**Issue by fvdhsss** [ZhenyuTANG2023/data_selection#2]
When I run the experiment, the interface displays: 

`petrel_client is not installed, petrel oss cannot be used currently.`

However, the experiment still runs. Will this affect the results? I have installed the petrel library, but this message still appears.

**Comment by ZhenyuTANG2023** [comment]
The results will not be affected. `petrel oss` is associated to a file storage service I was using, and I have disabled it in this repo.

**Comment by fvdhsss** [comment]
> 结果不会受到影响。 与我正在使用的文件存储服务相关联，并且我已在此存储库中禁用它。`petrel oss`

thanks!
