### ISSUE TITLE
lack of npy files

### ISSUE THREAD

**Issue by fvdhsss** [ZhenyuTANG2023/data_selection#3]
I noticed that the `gatters` file has built-in methods for processing datasets like SVHN, CIFAR-100, etc. However, when I change the dataset to SVHN in the YAML file, it shows that the` .npy` file is missing. Do I need to generate it manually? Is this how other datasets are processed as well?

**Comment by ZhenyuTANG2023** [comment]
Is the `.npy` missing error triggered in [line 37 in the `utils/getters.py` file](https://github.com/ZhenyuTANG2023/data_selection/blob/c3b527468408c89f5737b6bc98412c50e2ee3b34/utils/getters.py#L37)? By setting `download=True`, a `.mat` file of SVHN training or testing split should be downloaded to local folders. Could you provide a more detailed error log?

**Comment by fvdhsss** [comment]
Sorry for getting back to you so late.

> 
> 2024-11-18 18:11:52,075 - adaptive_selection.py[line:242] - ERROR: [Errno 2] No such file or directory: './data/coreset/ours/svhn.npy'
> 2024-11-18 18:11:52,075 - adaptive_selection.py[line:243] - INFO: Traceback information:
> Traceback (most recent call last):
>   File "adaptive_selection.py", line 229, in train
>     train_loss, valid_loss, train_epochs_loss, valid_epochs_loss = training_loop(args, logger, valuator, selector,
>   File "adaptive_selection.py", line 69, in training_loop
>     train_indices = np.load(f"./data/coreset/{coreset_name}/{args.dataset}.npy").tolist()
>   File "C:\Users\zrway\anaconda3\envs\select\lib\site-packages\numpy\lib\npyio.py", line 390, in load
>     fid = stack.enter_context(open(os_fspath(file), "rb"))
> FileNotFoundError: [Errno 2] No such file or directory: './data/coreset/ours/svhn.npy'

**Comment by ZhenyuTANG2023** [comment]
I see. Yes, you have to regenerate the `.npy` file for SVHN manually by running `coreset_selection.py` (see README). The provided `.npy` files (for CIFAR-10 *etc*) were created using the same process.

**Comment by fvdhsss** [comment]
Got it, I'll give it a try.
